### ISSUE TITLE
Run aksip

### ISSUE THREAD

**Issue by agungsaputro** [cmendible/aksip#1]
How run aksip ?

**Comment by cmendible** [comment]
**aksip** is a command line tool.

## On Windows:

Download de latest version using PowerShell:

```
Invoke-WebRequest -Uri https://github.com/cmendible/aksip/releases/download/v0.2.0/aksip_windows_amd64.exe -OutFile aksip.exe
```

Then from the command line run:

```
.\aksip
```

---

## On linux:

Download de latest version:

```
wget -O- https://github.com/cmendible/aksip/releases/download/v0.2.0/aksip_linux_amd64 > aksip
```

Then from the command line run:

```
.\aksip
```

---

## Get help on parameters:

Run:

```
.\aksip -h
```

Also you can check my post: [Plan IP addressing for AKS configured with Azure CNI Networking](https://carlos.mendible.com/2021/07/09/plan-ip-addressing-for-aks-configured-with-azure-cni-networking/)

**Comment by agungsaputro** [comment]
oke thanks
